---
- hosts: all
  serial: 1
  become: yes
  gather_facts: yes
  ignore_errors: true
  vars:
    bmc_server: 127.0.0.1
    rt_server1: 127.0.0.1
    rt_server2: 127.0.0.1
    av_server1: 127.0.0.1
    av_server2: 127.0.0.1
    av_lua_server: 127.0.0.1
    yum_server: 127.0.0.1
    http_port: 80
    https_port: 443
    
  tasks:
  - name: Try and find SERVER in bp.conf
    command: "awk '$0~/^SERVER =/ {print$3}' /usr/openv/netbackup/bp.conf"
    register: server
   
  - name: Check Netbackup connectivity to SERVER port 1556
    wait_for: 
      host: "{{ item }}"
      port: 1556
      timeout: 2
    with_items: "{{ server.stdout_lines }}"

  - name: Check BMC connectivity to "{{ bmc_server }}" port "{{ http_port }}"
    wait_for: 
      host: "{{ bmc_server }}"
      port: "{{ http_port }}"
      timeout: 2

  - name: Check BMC rt server connectivity to "{{ rt_server1 }}" port 2059
    wait_for: 
      host:  "{{ rt_server1 }}"
      port: 2059
      timeout: 2

  - name: Check BMC rt server connectivity to "{{ rt_server2 }}" port 2059
    wait_for: 
      host: "{{ rt_server2 }}"
      port: 2059
      timeout: 2

  - name: Check SEP AV server connectivity to "{{ av_server1 }}" port "{{ https_port }}" REDHAT ONLY
    when: ansible_os_family == "RedHat"
    wait_for: 
      host: "{{ av_server1 }}"
      port: "{{ https_port }}"
      timeout: 2

  - name: Check SEP AV server connectivity to "{{ av_server2 }}" port "{{ https_port }}" REDHAT ONLY
    when: ansible_os_family == "RedHat"
    wait_for: 
      host: "{{ av_server2 }}"
      port: "{{ https_port }}"
      timeout: 2

  - name: Check SEP AV  LUA server connectivity to "{{ av_lua_server }}" port 7070 REDHAT ONLY
    when: ansible_os_family == "RedHat"
    wait_for: 
      host: "{{ av_lua_server }}"
      port: 7070
      timeout: 2

  - name: Check YUM server connectivity to "{{ yum_server }}" port "{{ http_port }}" REDHAT ONLY
    when: ansible_os_family == "RedHat"
    wait_for: 
      host: "{{ yum_server }}"
      port: "{{ http_port }}"
      timeout: 2
