---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Rebooting Solaris
        shell: "sleep 5 && /usr/sbin/shutdown -y -g0 -i6 "Rebooted by ansible""
        async: 1
        poll: 0

    - name: wait for Solaris system to reboot
        wait_for_connection:
          connection_timeout: 40
          sleep: 5
          delay: 5
          timeout: 120
