---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: Setting yum proxy configuration
    when: ansible_os_family == "RedHat" and ansible_distribution_version > "5" # Check the host is Redhat 5 and above
    lineinfile:
      state: present
      path: /etc/yum.conf
      line: 'proxy=http://192.168.1.33:3128'
      
  - name: Setting yum exclude configuration
    when: ansible_os_family == "RedHat" and ansible_distribution_version > "5" # Check the host is Redhat 5 and above
    lineinfile:
      state: present
      path: /etc/yum.conf
      line: 'exclude=java* firefox*'

  - name: Checking that YUM works
    yum:
      list: repos
    register: repo_list

  - name: Getting yum repo_list
    debug: msg=" Yum configured as follows {{ repo_list }}"

  - name: Upgrade all packages
    when: ansible_os_family == "RedHat" and ansible_distribution_version > "5" # Check the host is Redhat 5 and above
    yum:
      name: '*'
      state: latest
